--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4 (Debian 15.4-1.pgdg120+1)
-- Dumped by pg_dump version 16.0

-- Started on 2024-01-05 20:40:48

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16417)
-- Name: area; Type: TABLE; Schema: public; Owner: fantasy-map-app
--

CREATE TABLE public.area (
    area_id integer NOT NULL,
    title character varying(80) NOT NULL,
    color character varying(7) NOT NULL,
    border_color character varying(7),
    map_id integer NOT NULL,
    path text NOT NULL,
    blog_id integer
);


ALTER TABLE public.area OWNER TO "fantasy-map-app";

--
-- TOC entry 218 (class 1259 OID 16416)
-- Name: area_area_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE public.area ALTER COLUMN area_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.area_area_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16441)
-- Name: blog; Type: TABLE; Schema: public; Owner: fantasy-map-app
--

CREATE TABLE public.blog (
    blog_id integer NOT NULL,
    title character varying(128) NOT NULL,
    content text,
    author_id integer,
    image_b64 text
);


ALTER TABLE public.blog OWNER TO "fantasy-map-app";

--
-- TOC entry 222 (class 1259 OID 16440)
-- Name: blog_blog_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE public.blog ALTER COLUMN blog_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blog_blog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16390)
-- Name: map; Type: TABLE; Schema: public; Owner: fantasy-map-app
--

CREATE TABLE public.map (
    map_id integer NOT NULL,
    title character varying(255) NOT NULL,
    image_thumb_bytes bytea NOT NULL,
    image_b64 text NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.map OWNER TO "fantasy-map-app";

--
-- TOC entry 214 (class 1259 OID 16389)
-- Name: map_map_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE public.map ALTER COLUMN map_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.map_map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16406)
-- Name: point; Type: TABLE; Schema: public; Owner: fantasy-map-app
--

CREATE TABLE public.point (
    point_id integer NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    title character varying(64) NOT NULL,
    color character varying(7) NOT NULL,
    map_id integer NOT NULL,
    blog_id integer
);


ALTER TABLE public.point OWNER TO "fantasy-map-app";

--
-- TOC entry 216 (class 1259 OID 16405)
-- Name: point_point_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE public.point ALTER COLUMN point_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.point_point_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16430)
-- Name: user; Type: TABLE; Schema: public; Owner: fantasy-map-app
--

CREATE TABLE public."user" (
    user_id integer NOT NULL,
    name character varying(32) NOT NULL,
    password character varying(256) NOT NULL
);


ALTER TABLE public."user" OWNER TO "fantasy-map-app";

--
-- TOC entry 220 (class 1259 OID 16429)
-- Name: user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE public."user" ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3382 (class 0 OID 16417)
-- Dependencies: 219
-- Data for Name: area; Type: TABLE DATA; Schema: public; Owner: fantasy-map-app
--

COPY public.area (area_id, title, color, border_color, map_id, path, blog_id) FROM stdin;
\.


--
-- TOC entry 3386 (class 0 OID 16441)
-- Dependencies: 223
-- Data for Name: blog; Type: TABLE DATA; Schema: public; Owner: fantasy-map-app
--

COPY public.blog (blog_id, title, content, author_id, image_b64) FROM stdin;
\.


--
-- TOC entry 3378 (class 0 OID 16390)
-- Dependencies: 215
-- Data for Name: map; Type: TABLE DATA; Schema: public; Owner: fantasy-map-app
--

COPY public.map (map_id, title, image_thumb_bytes, image_b64, user_id) FROM stdin;
\.


--
-- TOC entry 3380 (class 0 OID 16406)
-- Dependencies: 217
-- Data for Name: point; Type: TABLE DATA; Schema: public; Owner: fantasy-map-app
--

COPY public.point (point_id, x, y, title, color, map_id, blog_id) FROM stdin;
\.


--
-- TOC entry 3384 (class 0 OID 16430)
-- Dependencies: 221
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: fantasy-map-app
--

COPY public."user" (user_id, name, password) FROM stdin;
\.


--
-- TOC entry 3392 (class 0 OID 0)
-- Dependencies: 218
-- Name: area_area_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy-map-app
--

SELECT pg_catalog.setval('public.area_area_id_seq', 1, false);


--
-- TOC entry 3393 (class 0 OID 0)
-- Dependencies: 222
-- Name: blog_blog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy-map-app
--

SELECT pg_catalog.setval('public.blog_blog_id_seq', 1, false);


--
-- TOC entry 3394 (class 0 OID 0)
-- Dependencies: 214
-- Name: map_map_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy-map-app
--

SELECT pg_catalog.setval('public.map_map_id_seq', 1, false);


--
-- TOC entry 3395 (class 0 OID 0)
-- Dependencies: 216
-- Name: point_point_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy-map-app
--

SELECT pg_catalog.setval('public.point_point_id_seq', 1, false);


--
-- TOC entry 3396 (class 0 OID 0)
-- Dependencies: 220
-- Name: user_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fantasy-map-app
--

SELECT pg_catalog.setval('public.user_user_id_seq', 1, false);


--
-- TOC entry 3224 (class 2606 OID 16423)
-- Name: area area_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE ONLY public.area
    ADD CONSTRAINT area_pkey PRIMARY KEY (area_id);


--
-- TOC entry 3228 (class 2606 OID 16447)
-- Name: blog blog_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE ONLY public.blog
    ADD CONSTRAINT blog_pkey PRIMARY KEY (blog_id);


--
-- TOC entry 3220 (class 2606 OID 16396)
-- Name: map map_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE ONLY public.map
    ADD CONSTRAINT map_pkey PRIMARY KEY (map_id);


--
-- TOC entry 3222 (class 2606 OID 16410)
-- Name: point point_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE ONLY public.point
    ADD CONSTRAINT point_pkey PRIMARY KEY (point_id);


--
-- TOC entry 3226 (class 2606 OID 16434)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);


--
-- TOC entry 3232 (class 2606 OID 16458)
-- Name: area fk_area_blog_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE ONLY public.area
    ADD CONSTRAINT fk_area_blog_id FOREIGN KEY (blog_id) REFERENCES public.blog(blog_id);


--
-- TOC entry 3233 (class 2606 OID 16424)
-- Name: area fk_area_map_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE ONLY public.area
    ADD CONSTRAINT fk_area_map_id FOREIGN KEY (map_id) REFERENCES public.map(map_id) ON DELETE CASCADE;


--
-- TOC entry 3234 (class 2606 OID 16448)
-- Name: blog fk_blog_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE ONLY public.blog
    ADD CONSTRAINT fk_blog_user_id FOREIGN KEY (author_id) REFERENCES public."user"(user_id);


--
-- TOC entry 3229 (class 2606 OID 16435)
-- Name: map fk_map_user_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE ONLY public.map
    ADD CONSTRAINT fk_map_user_id FOREIGN KEY (user_id) REFERENCES public."user"(user_id);


--
-- TOC entry 3230 (class 2606 OID 16463)
-- Name: point fk_point_blog_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE ONLY public.point
    ADD CONSTRAINT fk_point_blog_id FOREIGN KEY (blog_id) REFERENCES public.blog(blog_id);


--
-- TOC entry 3231 (class 2606 OID 16411)
-- Name: point fk_point_map_id; Type: FK CONSTRAINT; Schema: public; Owner: fantasy-map-app
--

ALTER TABLE ONLY public.point
    ADD CONSTRAINT fk_point_map_id FOREIGN KEY (map_id) REFERENCES public.map(map_id) ON DELETE CASCADE;


-- Completed on 2024-01-05 20:40:48

--
-- PostgreSQL database dump complete
--

